version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      home-assistant-test-stack:
        patterns:
          - homeassistant
          - pytest-homeassistant-custom-component
    ignore:
      - dependency-name: pytest
